#!/bin/bash
# query full-featured shell here
#
# functions	This file contains functions to be used by all
#		shell scripts of the beye

# Prefer these macros to full length text !
# These macros only return an error code - NO display is done
# Check how echo works in this /bin/sh
init_functions(){
case `echo -n` in
  -n)	echo_n=	     echo_c='\c';;	# SysV echo
  *)	echo_n='-n ' echo_c=	;;	# BSD echo
esac
}

log(){
    echo "$@" >>"$TMPLOG"
}

log_file(){
    log BEGIN $1
    cat -n $1 >>"$TMPLOG"
    log END $1
}

echolog(){
    log "$@"
    echo "$@"
}

# "tr '[a-z]' '[A-Z]'" is a workaround for Solaris tr not grokking "tr a-z A-Z"
toupper(){
    echo "$@" | tr '[a-z]' '[A-Z]'
}

tolower(){
    echo "$@" | tr '[A-Z]' '[a-z]'
}

set_all(){
    value=$1
    shift
    for var in $*; do
        eval $var=$value
    done
}

set_weak(){
    value=$1
    shift
    for var; do
        eval : \${$var:=$value}
    done
}

pushvar(){
    for var in $*; do
        eval level=\${${var}_level:=0}
        eval ${var}_${level}="\$$var"
        eval ${var}_level=$(($level+1))
    done
}

popvar(){
    for var in $*; do
        eval level=\${${var}_level:-0}
        test $level = 0 && continue
        eval level=$(($level-1))
        eval $var="\${${var}_${level}}"
        eval ${var}_level=$level
        eval unset ${var}_${level}
    done
}

enable_weak(){
    set_weak yes $*
}

disable_weak(){
    set_weak no $*
}

do_enable_deep(){
    for var; do
        enabled $var && continue
        eval sel="\$${var}_select"
        eval sgs="\$${var}_suggest"
        pushvar var sgs
        enable_deep $sel
        popvar sgs
        enable_deep_weak $sgs
        popvar var
    done
}

enable_deep(){
    do_enable_deep $*
    enable $*
}

enable_deep_weak(){
    do_enable_deep $*
    enable_weak $*
}

enable(){
    set_all yes $*
}

disable(){
    set_all no $*
}

#enabled(){
#    test "${1#!}" = "$1" && op== || op=!=
#    eval test "x\$${1#!}" $op "xyes"
#}
#
#disabled(){
#    test "${1#!}" = "$1" && op== || op=!=
#    eval test "x\$${1#!}" $op "xno"
#}
enabled(){
    eval test "x\$$1" = "xyes"
}

disabled(){
    eval test "x\$$1" = "xno"
}

enabled_all(){
    for opt; do
        enabled $opt || return 1
    done
}

disabled_all(){
    for opt; do
        disabled $opt || return 1
    done
}

enabled_any(){
    for opt; do
        enabled $opt && return 0
    done
}

disabled_any(){
    for opt; do
        disabled $opt && return 0
    done
}

filter(){
    pat=$1
    shift
    for v; do
        eval "case $v in $pat) echo $v ;; esac"
    done
}

is_in(){
    value=$1
    shift
    for var in $*; do
        [ $var = $value ] && return 0
    done
    return 1
}

check_deps(){
    for cfg; do
        cfg="${cfg#!}"
        enabled ${cfg}_checking && die "Circular dependency for $cfg = ${cfg}"
        disabled ${cfg}_checking && continue
        enable ${cfg}_checking

        eval dep_all="\$${cfg}_deps"
        eval dep_any="\$${cfg}_deps_any"
        eval dep_sel="\$${cfg}_select"
        eval dep_sgs="\$${cfg}_suggest"

        pushvar cfg dep_all dep_any dep_sel dep_sgs
        check_deps $dep_all $dep_any $dep_sel $dep_sgs
        popvar cfg dep_all dep_any dep_sel dep_sgs

        enabled_all  $dep_all || disable $cfg
        enabled_any  $dep_any || disable $cfg
        disabled_any $dep_sel && disable $cfg

        if enabled $cfg; then
            eval dep_extralibs="\$${cfg}_extralibs"
            test -n "$dep_extralibs" && add_extralibs $dep_extralibs
            enable_deep $dep_sel
            enable_deep_weak $dep_sgs
        fi

        disable ${cfg}_checking
    done
}

print_config(){
    pfx=$1
    header=$2
    makefile=$3
    shift 3
    for cfg; do
        ucname="${pfx}`toupper $cfg`"
        if enabled $cfg; then
            echo "#define ${ucname} 1" >> $header
            echo "${ucname}=yes" >> $makefile
	else
#            echo "#undef ${ucname}" >> $header
            echo "${ucname}=no" >> $makefile
        fi
    done
}

check_type(){
    log check_type "$@"
    headers=$1
    type=$2
    shift 2
    disable $type
    incs=""
    for hdr in $headers; do
        incs="$incs
#include <$hdr>"
    done
    check_cc "$@" <<EOF && enable $type
$incs
$type v;
EOF
}

flags_saved(){
    (: ${SAVE_CFLAGS?}) 2>/dev/null
}

save_flags(){
    flags_saved && return
    SAVE_CFLAGS="$CFLAGS"
    SAVE_LDFLAGS="$LDFLAGS"
    SAVE_ASFLAGS="$ASFLAGS"
    SAVE_extralibs="$extralibs"
}

restore_flags(){
    flags_saved || return
    CFLAGS="$SAVE_CFLAGS"
    LDFLAGS="$SAVE_LDFLAGS"
    ASFLAGS="$SAVE_ASFLAGS"
    extralibs="$SAVE_extralibs"
    unset SAVE_CFLAGS
    unset SAVE_LDFLAGS
    unset SAVE_ASFLAGS
    unset SAVE_extralibs
}

temp_cflags(){
    save_flags
    CFLAGS="$CFLAGS $*"
}

temp_asflags(){
    save_flags
    ASFLAGS="$ASFLAGS $*"
}

temp_ldflags(){
    save_flags
    LDFLAGS="$LDFLAGS $*"
}

temp_extralibs(){
    save_flags
    extralibs="$extralibs $*"
}

append(){
    var=$1
    shift
    flags_saved && eval "SAVE_$var=\"\$SAVE_$var $*\""
    eval "$var=\"\$$var $*\""
}

add_cflags(){
    append CFLAGS "$@"
}

add_cxxflags(){
    append CXXFLAGS "$@"
}

add_asflags(){
    append ASFLAGS "$@"
}

add_ldflags(){
    append LDFLAGS "$@"
}

add_ldxxflags(){
    append LDXXFLAGS "$@"
}

add_extralibs(){
    append extralibs "$@"
}

check_cmd(){
    log "$@"
    "$@" >>"$TMPLOG" 2>&1
}

check_cc(){
    log check_cc "$@"
    cat >$TMPC
    log_file $TMPC
    check_cmd $cc $CFLAGS "$@" -c -o $TMPO $TMPC
}

check_cxx(){
    log check_cxx "$@"
    cat >$TMPC
    log_file $TMPC
    check_cmd $cxx $CXXFLAGS "$@" -c -o $TMPO $TMPC
}

check_cpp(){
    log check_cpp "$@"
    cat >$TMPC
    log_file $TMPC
    check_cmd $cc $CFLAGS "$@" -E -o $TMPO $TMPC
}

test_asm(){
    log check_asm "$@"
    name="$1"
    asm="$2"
    shift 2
    check_cc "$@" <<EOF && return 0 || return 1
int foo(void){
    asm volatile($asm);
}
EOF
}

check_asm(){
    name="$1"
    test_asm "$@" && enable $name || disable $name
}

check_ld(){
    log check_ld "$@"
    check_cc || return
    check_cmd $cc $LDFLAGS -o $TMPE $TMPO $extralibs "$@"
}

check_ldxx(){
    log check_ld "$@"
    check_cxx || return
    check_cmd $cxx $LDFLAGS $LDXXFLAGS -o $TMPE $TMPO $extralibs "$@"
}

test_cflags(){
    log check_cflags "$@"
    check_cc "$@" <<EOF && return 0 || return 1
int x;
EOF
}

test_cxxflags(){
    log check_cxxflags "$@"
    check_cxx "$@" <<EOF && return 0 || return 1
int x;
EOF
}

check_cflags(){
    test_cflags "$@" && add_cflags "$@"
}

check_cxxflags(){
    test_cxxflags "$@" && add_cxxflags "$@"
}

is_in_cflags(){
    value=$1
    shift
    for var in $CFLAGS; do
        tmp=$(trim `echo $var | cut -d '=' -f 1`)
        [ $tmp = $value ] && return 0
    done
    return 1
}

is_in_cxxflags(){
    value=$1
    shift
    for var in $CXXFLAGS; do
        tmp=$(trim `echo $var | cut -d '=' -f 1`)
        [ $tmp = $value ] && return 0
    done
    return 1
}

test_ldflags(){
    log check_ldflags "$@"
    check_ld "$@" <<EOF && return 0 || return 1
int main(void){
    return 0;
}
EOF
}

check_ldflags(){
    test_ldflags "$@" && add_ldflags "$@"
}

check_ldxxflags(){
    test_ldxxflags "$@" && add_ldxxflags "$@"
}

check_header(){
    log check_header "$@"
    header=$1
    shift
    var=`echo $header | sed 's/[^A-Za-z0-9_]/_/g'`
    disable $var
    check_cpp "$@" <<EOF && enable $var
#include <$header>
int x;
EOF
}

check_headerl(){
    log check_headerl "$@"
    header=$1
    shift
    var=`echo $header | sed 's/[^A-Za-z0-9_]/_/g'`
    disable $var
    check_cpp "$@" <<EOF && enable $var
#include "$header"
int x;
EOF
}

check_lheader(){
    echocheck "$1"
    log check_lheader "$@"
    name=$1
    header=$2
    shift 2
    disable $name
    check_cpp "$@" <<EOF && enable $name
#include "$header"
int x;
EOF
    enabled $name && answer="yes" || answer="no"
    echores $answer
    enabled $name && return 0 || return 1
}

check_sheader(){
    echocheck "$1"
    log check_sheader "$@"
    name=$1
    header=$2
    shift 2
    disable $name
    check_cpp "$@" <<EOF && enable $name
#include <$header>
int x;
EOF
    enabled $name && answer="yes" || answer="no"
    echores $answer
    enabled $name && return 0 || return 1
}

check_func(){
    echocheck "$1"
    log check_func "$@"
    func=$1
    shift
    disable $func
    check_ld "$@" <<EOF && enable $func
extern int $func(void);
long x;
int main(void){
    x=(long)$func();
}
EOF
    enabled $func && answer="yes" || answer="no"
    echores $answer
    enabled $func && return 0 || return 1
}

check_func2(){
    echocheck "$2"
    log check_func2 "$@"
    headers=$1
    func=$2
    shift 2
    disable $func
    incs=""
    for hdr in $headers; do
        incs="$incs
#include <$hdr>"
    done
    check_ld "$@" <<EOF && enable $func
$incs
long x;
int main(void){
    x=(long)$func;
    return 0;
}
EOF
    enabled $func && answer="yes" || answer="no"
    echores $answer
    enabled $func && return 0 || return 1
}

check_func3(){
    echocheck "$3"
    log check_func3 "$@"
    defines=$1
    headers=$2
    func=$3
    shift 3
    disable $func
    defs=""
    for dfn in $defines; do
        defs="$defs
#define $dfn 1"
    done
    incs=""
    for hdr in $headers; do
        incs="$incs
#include <$hdr>"
    done
    check_ld "$@" <<EOF && enable $func
$defs
$incs
long x;
int main(void){
    x=(long)$func;
    return 0;
}
EOF
    enabled $func && answer="yes" || answer="no"
    echores $answer
    enabled $func && return 0 || return 1
}

check_class2(){
    echocheck "$2"
    log check_class2 "$@"
    headers=$1
    class=$2
    shift 2
    disable $class
    incs=""
    for hdr in $headers; do
        incs="$incs
#include <$hdr>"
    done
    check_ldxx "$@" <<EOF && enable $class
$incs
class $class;
int main(void){
    return 0;
}
EOF
    enabled $class && answer="yes" || answer="no"
    echores $answer
    enabled $class && return 0 || return 1
}

check_lfunc2(){
    echocheck "$2"
    log check_lfunc2 "$@"
    headers=$1
    func=$2
    shift 2
    disable $func
    incs=""
    for hdr in $headers; do
        incs="$incs
#include "$hdr""
    done
    check_ld "$@" <<EOF && enable $func
$incs
long x;
int main(void){
    x=(long)$func;
    return 0;
}
EOF
    enabled $func && answer="yes" || answer="no"
    echores $answer
    enabled $func && return 0 || return 1
}

check_lfunc3(){
    echocheck "$3"
    log check_lfunc3 "$@"
    defines=$1
    headers=$2
    func=$3
    shift 3
    disable $func
    defs=""
    for dfn in $defines; do
        defs="$defs
#define $dfn 1"
    done
    incs=""
    for hdr in $headers; do
        incs="$incs
#include "$hdr""
    done
    check_ld "$@" <<EOF && enable $func
$defs
$incs
long x;
int main(void){
    x=(long)$func;
    return 0;
}
EOF
    enabled $func && answer="yes" || answer="no"
    echores $answer
    enabled $func && return 0 || return 1
}

check_lib(){
    log check_lib "$@"
    header="$1"
    func="$2"
    shift 2
    temp_extralibs "$@"
    check_header $header && check_func $func && add_extralibs "$@"
    err=$?
    restore_flags
    return $err
}

check_lib2(){
    log check_lib2 "$@"
    headers="$1"
    func="$2"
    shift 2
    temp_extralibs "$@"
    check_func2 "$headers" $func && add_extralibs "$@"
    err=$?
    restore_flags
    return $err
}

check_lib3(){
    log check_lib3 "$@"
    defs="$1"
    headers="$2"
    func="$3"
    shift 3
    temp_extralibs "$@"
    check_func3 "$defs" "$headers" $func && add_extralibs "$@"
    err=$?
    restore_flags
    return $err
}

check_libxx2(){
    log check_libxx2 "$@"
    headers="$1"
    class="$2"
    shift 2
    temp_extralibs "$@"
    check_class2 "$headers" $class && add_extralibs "$@"
    err=$?
    restore_flags
    return $err
}

check_llib(){
    log check_lib "$@"
    header="$1"
    func="$2"
    shift 2
    temp_extralibs "$@"
    check_headerl $header && check_func $func && add_extralibs "$@"
    err=$?
    restore_flags
    return $err
}

check_llib2(){
    log check_llib2 "$@"
    headers="$1"
    func="$2"
    shift 2
    temp_extralibs "$@"
    check_lfunc2 "$headers" $func && add_extralibs "$@"
    err=$?
    restore_flags
    return $err
}

check_llib3(){
    log check_llib3 "$@"
    defs="$1"
    headers="$2"
    func="$3"
    shift 3
    temp_extralibs "$@"
    check_lfunc3 "$defs" "$headers" $func && add_extralibs "$@"
    err=$?
    restore_flags
    return $err
}

check_macro(){
    echocheck "$1"
    log check_macro "$@"
    macro=$1
    shift
    disable $macro
    check_cc "$@" <<EOF && enable $macro
#ifndef $macro
#error Macro $macro is undefined
#endif
int x;
EOF
    enabled $macro && answer="yes" || answer="no"
    echores $answer
    enabled $macro && return 0 || return 1
}

check_macro2(){
    echocheck "$2"
    log check_macro2 "$@"
    headers=$1
    macro=$2
    shift 2
    disable $macro
    incs=""
    for hdr in $headers; do
        incs="$incs
#include <$hdr>"
    done
    check_cc "$@" <<EOF && enable $macro
$incs
#ifndef $macro
#error Macro $macro is undefined
#endif
int x;
EOF
    enabled $macro && answer="yes" || answer="no"
    echores $answer
    enabled $macro && return 0 || return 1
}

check_macro3(){
    echocheck "$3"
    log check_macro3 "$@"
    defines=$1
    headers=$2
    macro=$3
    shift 3
    disable $macro
    defs=""
    for dfn in $defines; do
        defs="$defs
#define $dfn 1"
    done
    incs=""
    for hdr in $headers; do
        incs="$incs
#include <$hdr>"
    done
    check_cc "$@" <<EOF && enable $macro
$defs
$incs
#ifndef $macro
#error Macro $macro is undefined
#endif
int x;
EOF
    enabled $macro && answer="yes" || answer="no"
    echores $answer
    enabled $macro && return 0 || return 1
}

check_lmacro2(){
    echocheck "$2"
    log check_lmacro2 "$@"
    headers=$1
    macro=$2
    shift 2
    disable $macro
    incs=""
    for hdr in $headers; do
        incs="$incs
#include "$hdr""
    done
    check_cc "$@" <<EOF && enable $macro
$incs
#ifndef $macro
#error Macro $macro is undefined
#endif
int x;
EOF
    enabled $macro && answer="yes" || answer="no"
    echores $answer
    enabled $macro && return 0 || return 1
}

check_lmacro3(){
    echocheck "$3"
    log check_lmacro3 "$@"
    defines=$1
    headers=$2
    macro=$3
    shift 3
    disable $macro
    defs=""
    for dfn in $defines; do
        defs="$defs
#define $dfn 1"
    done
    incs=""
    for hdr in $headers; do
        incs="$incs
#include "$hdr""
    done
    check_cc "$@" <<EOF && enable $macro
$defs
$incs
#ifndef $macro
#error Macro $macro is undefined
#endif
int x;
EOF
    enabled $macro && answer="yes" || answer="no"
    echores $answer
    enabled $macro && return 0 || return 1
}

check_exec(){
    check_ld "$@" && { enabled cross_compile || $TMPE >>"$TMPLOG" 2>&1; }
}

require(){
    echocheck "$1"
    name="$1"
    header="$2"
    func="$3"
    shift 3
    disable $name
    check_lib $header $func "$@" && enable $name
    answer="no"
    enabled $name && answer="yes"
    echores $answer
}

require2(){
    echocheck "$1"
    name="$1"
    headers="$2"
    func="$3"
    shift 3
    disable $name
    check_lib2 "$headers" $func "$@" && enable $name
    answer="no"
    enabled $name && answer="yes"
    echores $answer
}

require3(){
    echocheck "$1"
    name="$1"
    headers="$2"
    macros="$3"
    func="$4"
    shift 4
    disable $name
    check_macro2 "$headers" $macros && check_lib2 "$headers" $func "$@" && enable $name
    answer="no"
    enabled $name && answer="yes"
    echores $answer
}

xxrequire2(){
    echocheck "$1"
    name="$1"
    headers="$2"
    class="$3"
    shift 3
    disable $name
    check_libxx2 "$headers" $class "$@" && enable $name
    answer="no"
    enabled $name && answer="yes"
    echores $answer
}

lrequire(){
    echocheck "$1"
    name="$1"
    header="$2"
    func="$3"
    shift 3
    disable $name
    check_llib $header $func "$@" && enable $name
    answer="no"
    enabled $name && answer="yes"
    echores $answer
}

lrequire2(){
    echocheck "$1"
    name="$1"
    headers="$2"
    func="$3"
    shift 3
    disable $name
    check_llib2 "$headers" $func "$@" && enable $name
    answer="no"
    enabled $name && answer="yes"
    echores $answer
}

lrequire3(){
    echocheck "$1"
    name="$1"
    headers="$2"
    macros="$3"
    func="$4"
    shift 4
    disable $name
    check_lmacro2 "$headers" $macros && check_lib2 "$headers" $func "$@" && enable $name
    answer="no"
    enabled $name && answer="yes"
    echores $answer
}

check_foo_config(){
    cfg=$1
    pkg=$2
    header=$3
    func=$4
    shift 4
    disable $cfg
    check_cmd ${pkg}-config --version
    err=$?
    if test "$err" = 0; then
        temp_cflags `${pkg}-config --cflags`
        temp_extralibs `${pkg}-config --libs`
        check_lib "$@" $header $func && enable $cfg
    fi
    return $err
}

apply(){
    file=$1
    shift
    "$@" < "$file" > "$file.tmp" && mv "$file.tmp" "$file" || rm "$file.tmp"
}

# Below is our OLD stuff

cc_check() {
  echo >> "$TMPLOG"
  cat "$TMPC" >> "$TMPLOG"
  echo >> "$TMPLOG"
  ( check_cmd $cc $CFLAGS $inc_extra $ld_static $ld_extra "$TMPC" -o "$TMPO" "$@" ) >> "$TMPLOG" 2>&1
  TMP="$?"
  echo >> "$TMPLOG"
  echo "ldd $TMPO" >> "$TMPLOG"
  ( ldd "$TMPO" ) >> "$TMPLOG" 2>&1
  echo >> "$TMPLOG"
  return "$TMP"
}

cxx_check() {
  echo >> "$TMPLOG"
  cat "$TMPC" >> "$TMPLOG"
  echo >> "$TMPLOG"
  ( check_cmd $cxx $CXXFLAGS $inc_extra $ld_static $ld_extra "$TMPC" -o "$TMPO" "$@" ) >> "$TMPLOG" 2>&1
  TMP="$?"
  echo >> "$TMPLOG"
  echo "ldd $TMPO" >> "$TMPLOG"
  ( ldd "$TMPO" ) >> "$TMPLOG" 2>&1
  echo >> "$TMPLOG"
  return "$TMP"
}

# Display error message, flushes tempfile, exit
warning() {
  log "Warning: $@"
  echo
  echo "Warning: $@" >&2
  echo >&2
}

die() {
  log "Error: $@"
  echo
  echo "Error: $@" >&2
  echo >&2
  rmtmps
  echo "Check "$TMPLOG" if you do not understand why it failed."
  exit 1
}

mktmps() {
local I
for I in "$TMPDIR" "$TEMPDIR" "/tmp" ; do
  test "$I" && break
done
TMPLOG="configure.log"
rm -f "$TMPLOG"
TMPC="$I/beye-conf-$RANDOM-$$.c"
TMPCPP="$I/beye-conf-$RANDOM-$$.cpp"
TMPO="$I/beye-conf-$RANDOM-$$.o"
TMPE="$I/beye-conf-$RANDOM-$$.exe"
TMPS="$I/beye-conf-$RANDOM-$$.S"
TMPH="$I/beye-conf-$RANDOM-$$.h"
}

rmtmps() {
  rm -f "$TMPO" "$TMPC" "$TMPS" "$TMPCPP" "$TMPH" "$TMPE"
}

# OS test booleans functions
issystem() {
  test "`echo $host_os | tr A-Z a-z`" = "`echo $1 | tr A-Z a-z`"
}
linux()   { issystem "Linux-GNU"; return "$?" ; }
sunos()   { issystem "SunOS"   ; return "$?" ; }
hpux()    { issystem "HP-UX"   ; return "$?" ; }
irix()    { issystem "IRIX"    ; return "$?" ; }
aix()     { issystem "AIX"     ; return "$?" ; }
dos()     { issystem "DJGPP"   ; return "$?" ; }
os2()     { issystem "EMX-OS2" ; return "$?" ; }
cygwin()  { issystem "CYGWIN"  ; return "$?" ; }
mingw32() { issystem "MINGW32" ; return "$?" ; }
win32()   { cygwin || mingw32  ; return "$?" ; }
freebsd() { issystem "FreeBSD" ; return "$?" ; }
netbsd()  { issystem "NetBSD"  ; return "$?" ; }
bsdos()   { issystem "BSD/OS"  ; return "$?" ; }
openbsd() { issystem "OpenBSD" ; return "$?" ; }
bsd()     { freebsd || netbsd || bsdos || openbsd ; return "$?" ; }
qnx()     { issystem "QNX"     ; return "$?" ; }
qnxnto()  { issystem "QNXNTO"  ; return "$?" ; }
darwin()  { issystem "Darwin"  ; return "$?" ; }
gnu()     { issystem "GNU"     ; return "$?" ; }
morphos() { issystem "MorphOS" ; return "$?" ; }
beos()    { issystem "BEOS"    ; return "$?" ; }

# arch test boolean functions
x86_32() {
  case "$host_arch" in
    i*86|x86|x86pc|k5|k6|k6-2|k6-3|pentium*|athlon*)
	return 0
	;;
    *)  return 1
	;;
  esac
  return 1
}

x86_64() {
  case "$host_arch" in
    x86_64|amd64)
	return 0
	;;
    *)  return 1
	;;
  esac
  return 1
}

x86() {
  x86_32 && return 0
  x86_64 && return 0
  return 1
}

ppc() {
  case "$host_arch" in
    ppc) return 0;;
    *) return 1;;
  esac
}

mips() {
  case "$host_arch" in
    mips) return 0;;
    *) return 1;;
  esac
}

alpha() {
  case "$host_arch" in
    alpha) return 0 ;;
    *) return 1 ;;
  esac
}

arm() {
  case "$host_arch" in
    arm) return 0 ;;
    *) return 1 ;;
  esac
}


# not boolean test: implement the posix shell "!" operator for a
# non-posix /bin/sh.
#   usage:  not {command}
# returns exit status "success" when the execution of "command"
# fails.
not() {
  eval "$@"
  test $? -ne 0
}

# Use this before starting a check
echocheck() {
  if test "$echocheked" != "yes"; then
  echocheked=yes
  log "============ Checking for $@ ============"
  echo $echo_n "Checking for $@ ... "$echo_c
  fi
}

# Use this to echo the results of a check
echores() {
  if test "$echocheked" = "yes"; then
  echocheked=no
  log "Result is: $@"
  log "##########################################"
  log ""
  echo "$@"
  fi
}
#############################################################################


# Guessing target system
guess_target() {
echocheck "build system type"
local config_mak=$1
local config_h=$2
config_guess="./config.guess"
config_sub="./config.sub"
if test -z "$build" ; then
build=`$config_guess`
test -z "$build" && echores "cannot guess build type; you must specify one"
fi
# Canonize it
$config_sub sun4 >/dev/null 2>&1 || echores "cannot run $config_sub"
build=`$config_sub $build`
echores "$build"
build_cpu=`echo $build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
build_vendor=`echo $build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
build_os=`echo $build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
echocheck "host system type"
if test -z "$host" ; then
host=$build
fi
host=`$config_sub $host`
host_cpu=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
host_vendor=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
host_os=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
echores "$host"

# Printout architecture
case "$host_cpu" in
  i*86)
  host_arch="x86"
  icpu=`echo $host_cpu | sed -n 's/^i\([0-9]*\)$/\1/p'`
    ;;
  *)
  host_arch=$host_cpu
  icpu=$host_cpu
    ;;
esac
def_words_endian='#define WORDS_BIGENDIAN 1'
x86   && def_words_endian="#undef WORDS_BIGENDIAN"
arm   && def_words_endian="#undef WORDS_BIGENDIAN"
alpha && def_words_endian="#undef WORDS_BIGENDIAN"

lc_host_arch=`echo $host_arch | tr [:lower:] [:upper:]`
lc_host_os=`echo $host_os | tr [:lower:] [:upper:]`
lc_host_sys=$lc_host_os
if win32 ; then
lc_host_os=WIN32
slibsuf=".dll"
else
slibsuf=".so"
fi
if linux ; then
lc_host_os=LINUX
fi
#tune architecture
x86_64 && lc_host_arch="X86_64"
x86_64 && icpu="k8"
x86_32 && lc_host_arch="X86"
x86_32 && icpu="athlon" # it enables -m3dnowa support which can't be enabled through command line
lc_host_os=`echo $lc_host_os | sed 's/[^A-Za-z0-9_]/_/g'`

cat > $config_mak << EOF
# -------- Generated by guess_target() -----------
TARGET_OS = $lc_host_os
TARGET_SYS = $lc_host_sys
TARGET_ARCH_$lc_host_arch = yes
TARGET_CPU = $icpu
SLIBSUF = $slibsuf
EOF

cat > $config_h << EOF
/* -------- Generated by guess_target() ----------- */
#ifndef BEYE_CONFIG_ARCH
#define BEYE_CONFIG_ARCH 1
#define ARCH_$lc_host_arch 1
#define __CPU__ $icpu
/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
$def_words_endian
#define TARGET_$lc_host_os 1
#define SLIBSUFFIX "$slibsuf"
EOF

case "$lc_host_arch" in
  X86)
    echo "#define ARCH_X86_32 1" >> $config_h
    ;;
  *)
    ;;
esac
}


test_optimizations() {
local config_mak=$1
local config_h=$2


locarch=""
if x86_64 ; then
locarch="-march=$icpu -m64"
add_ldflags -m64
add_asflags --64
elif x86_32 ; then
locarch="-march=$icpu -m32"
add_ldflags -m32
add_asflags --32
fi

# agree with user-defined architecture/tuning here
if enabled gcc44_workaround ; then
is_in_cflags "-march" || check_cflags "-march=native"
is_in_cflags "-mtune" || check_cflags "-mtune=native"
else
is_in_cflags "-march" || check_cflags $locarch
is_in_cflags "-mtune" || check_cflags "-mtune=generic"
fi
if enabled profile || test $debug -gt 2 || enabled gcov; then
    add_cflags "-O2 -fno-builtin"
if enabled profile ; then
    add_cflags  "-pg"
    add_ldflags "-pg"
fi
if test $debug -gt 0 ; then
    add_cflags "-g$debug"
    add_ldflags "-g$debug"
fi
if enabled gcov ; then
add_cflags "-fprofile-arcs -ftest-coverage"
add_extralibs "-lgcov"
fi
else
  is_in_cflags "-O2" || add_cflags "-O2"
  mips   || check_cflags "-pipe"
  x86_32 && check_cflags "-fomit-frame-pointer"
# modern glibc provides much better optimized versions of built-in functions
  x86_64 && add_cflags " -fno-builtin-function"
# -fomit-frame-pointer is not needed for x86_64
fi
# -ffast-math produces incorrect output in 64-bit mode on x86_64 cpus. Tested with many gcc-4.x series
is_in_cflags "-fno-fast-math" || check_cflags "-fno-fast-math"
is_in_cflags "-mfancy-math-387" || check_cflags "-mfancy-math-387"
is_in_cflags "-fno-math-errno" || check_cflags "-fno-math-errno"
is_in_cflags "-fno-signed-zeros" || check_cflags "-fno-signed-zeros"
# it seems that -mtune=generic doesn't prevent generation of SSE4 opcodes for i686 arch
check_cflags "-fno-tree-vectorize"
check_cflags "-fno-tree-vect-loop-version"
check_cflags "-fno-vect-cost-model"

disable mmx_test
x86 && enable mmx_test
enabled gcc44_workaround && disable mmx_test
if enabled mmx_test ; then
check_cflags -mmmx
check_cflags -m3dnow
check_cflags -msse
check_cflags -msse2
check_cflags -msse3
check_cflags -mssse3
check_cflags -msse4
check_cflags -mpclmul
check_cflags -maes
check_cflags -mavx
fi
# TODO: remove this block
cat >> $config_h << EOF
/* Extension defines */
#define FPU_CLOBBERED "st","st(1)","st(2)","st(3)","st(4)","st(5)","st(6)","st(7)"
#define MMX_CLOBBERED "mm0","mm1","mm2","mm3","mm4","mm5","mm6","mm7"
#define SSE_CLOBBERED "xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7"
EOF

if (alpha) ; then
  echocheck "CPU type"
cat > $TMPC << EOF
int main(void) {
    unsigned long ver, mask;
    asm ("implver %0" : "=r" (ver));
    asm ("amask %1, %0" : "=r" (mask) : "r" (-1));
    printf("%ld-%x\n", ver, ~mask);
    return 0;
}
EOF
  def_mvi='#undef HAVE_MVI'
  $cc -o "$TMPO" "$TMPC"
  lc_ver_mask=`$TMPO`
  case "$lc_ver_mask" in
    0-0) proc="ev4" ;;
    1-0) proc="ev5" ;;
    1-1) proc="ev56" ;;
    1-101) proc="pca56"; def_mvi='#define HAVE_MVI 1' ;;
    2-303) proc="ev6"; def_mvi='#define HAVE_MVI 1' ;;
    2-307) proc="ev67"; def_mvi='#define HAVE_MVI 1' ;;
    2-1307) proc="ev68"; def_mvi='#define HAVE_MVI 1' ;;
  esac
  echores "$proc"
cat >> $config_h << EOF
$def_mvi
EOF
fi
cat >> $config_h << EOF
#endif /* BEYE_CONFIG_ARCH */
EOF
}

trim()
{
    local trimmed=$1
    trimmed=${trimmed%% }
    trimmed=${trimmed## }
    echo $trimmed
}

print_help(){
echo "Usage: $0 [OPTION]... [VAR=VALUE]...

To assign environment variables (e.g., CC, CFLAGS...), specify them as
VAR=VALUE.  See below for descriptions of some of the useful variables.

Defaults for the options are specified in brackets."
local list="$1[*]"
list=${!list}
local index=1
OLD_IFS=$IFS
IFS=
while true
do
    local line=$(trim `echo $list | cut -d ',' -f $index`)
    test -z $line && break
    local opt=$(trim `echo $line | cut -d '|' -f 1`)
    local descr=$(trim `echo $line | cut -s -d '|' -f 2`)
    local opref=$(trim `echo $line | cut -s -d '|' -f 3`)
    echo "$descr:"
    opt="$opt[*]"
    opt=${!opt}
    local i=1
    while true
    do
	local oval=$(trim `echo $opt | cut -d ',' -f $i`)
	test -z $oval && break
	local oopt=$(trim `echo $oval | cut -d '|' -f 1`)
	local odesc=$(trim `echo $oval | cut -s -d '|' -f 2`)
	local odef=$(trim `echo $oval | cut -s -d '|' -f 3`)
	printf "  "
	test -z $opref || printf "%s" $opref
#	((for(j=0;j<(25-lpref);j++))) printf " "
	printf "%-25s %s " ${oopt//_/-} $odesc
	test -z $odef && echo "" || echo "[$odef]"
	(( i++ ))
    done
    (( index++ ))
done
IFS=$OLD_IFS
}

make_defaults(){
local list="$1[*]"
list=${!list}
local index=1
OLD_IFS=$IFS
IFS=
while true
do
    local line=$(trim `echo $list | cut -d ',' -f $index`)
    test -z $line && break
    local opt=$(trim `echo $line | cut -d '|' -f 1`)
    opt="$opt[*]"
    opt=${!opt}
    local i=1
    while true
    do
	local oval=$(trim `echo $opt | cut -d ',' -f $i`)
	test -z $oval && break
	local oopt=$(trim `echo $oval | cut -d '|' -f 1`)
	local odef=$(trim `echo $oval | cut -s -d '|' -f 3`)
	eval "assigned_val=\$$oopt"
	if test -z $assigned_val ; then
	    test -z $odef || eval "$oopt=\"$odef\""
	fi
	(( i++ ))
    done
    (( index++ ))
done
IFS=$OLD_IFS
}

in_list(){
local list="$1[*]"
list=${!list}
local index=1
OLD_IFS=$IFS
IFS=
while true
do
    local line=$(trim `echo $list | cut -d ',' -f $index`)
    test -z $line && break
    local opt=$(trim `echo $line | cut -d '|' -f 1`)
    opt="$opt[*]"
    opt=${!opt}
    local i=1
    while true
    do
	local oval=$(trim `echo $opt | cut -d ',' -f $i`)
	test -z $oval && break
	local oopt=$(trim `echo $oval | cut -d '|' -f 1`)
	if test $2 = $oopt ; then
	    IFS=$OLD_IFS
	    return 0
	fi
	(( i++ ))
    done
    (( index++ ))
done
IFS=$OLD_IFS
return 1
}

find_in_list(){
local list="$1[*]"
list=${!list}
local index=1
OLD_IFS=$IFS
IFS=
while true
do
    local line=$(trim `echo $list | cut -d ',' -f $index`)
    test -z $line && break
    local opt=$(trim `echo $line | cut -d '|' -f 1`)
    opt="$opt[*]"
    opt=${!opt}
    local i=1
    while true
    do
	local oval=$(trim `echo $opt | cut -d ',' -f $i`)
	test -z $oval && break
	local oopt=$(trim `echo $oval | cut -d '|' -f 1`)
	if test $2 = $oopt ; then
	    IFS=$OLD_IFS
	    echo "$oval"
	    return 0
	fi
	(( i++ ))
    done
    (( index++ ))
done
IFS=$OLD_IFS
return 1
}

show_homepage() {
local name=$1
local list="$2[*]"
list=${!list}
local descr
local site
echo "    $name"
if [ -z $3 ]; then
return
else
for i in $list ; do
    descr=`find_in_list "$3" $i`
    result=$?
    site=$(trim `echo $descr | cut -d '|' -f 3`)
    echo $echo_n "      $i " | tee -a $TMPLOG
    if test -z $site ; then
        echo $echo_c "" | tee -a $TMPLOG
    else
        echo $echo_c "(site: $site)" | tee -a $TMPLOG
    fi
done
fi
}

make_environment(){
local list="$1[*]"
list=${!list}
local i=1
OLD_IFS=$IFS
IFS=
while true
do
	local oval=$(trim `echo $list | cut -s -d ',' -f $i`)
	test -z $oval && break
	local oopt=$(trim `echo $oval | cut -d '|' -f 3`)
	local odef=$(trim `echo $oval | cut -s -d '|' -f 1`)
	eval "odef=\$$odef"
	test -z $oopt || test -z $odef || eval "$oopt=\"$odef\""
	(( i++ ))
done
IFS=$OLD_IFS
}

set_list(){
local list="$1[*]"
list=${!list}
local i=1
OLD_IFS=$IFS
IFS=
while true
do
	local oval=$(trim `echo $list | cut -s -d ',' -f $i`)
	test -z $oval && break
	local oopt=$(trim `echo $oval | cut -d '|' -f 1`)
	eval "$oopt=$2"
	(( i++ ))
done
IFS=$OLD_IFS
}

enable_list(){
set_list $1 yes
}

disable_list(){
set_list $1 no
}

check_pkg(){
    name=$1
    package=$2
    answer="no"
    echocheck $name
    enable $name
    $pkg_config $package --exists
    pkg_status="x$?"
    test $pkg_status != "x0" && disable $name
    if enabled $name ; then
	version=`echo $($pkg_config $package --modversion)`
	log "found version: $version of $package"
	check_cflags $($pkg_config $package --cflags) || disable $name
	check_ldflags $($pkg_config $package --libs) || disable $name
	answer=`echo "yes ($version)"`
    fi
    log "pkg-config --exists $package = $answer"
    echores $answer
}
